mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from tutorme import views

urlpatterns = [
    path('tutorme/', include('tutorme.urls')),
    path('tutorme/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('social/signup/', views.signup_redirect, name='signup_redirect'),
    # if allaut url(below) changed, let david know to change on google side
    path('', include("allauth.urls")),
    path('', views.start, name='landing page')
]

tutorme/urls.py
from django.urls import path, include
from . import views

app_name = "tutorme"

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('create_user/', views.create_user, name='create_user'),
    path('home/', views.go_home, name='home'),
    path('create_post/', views.create_post, name='create_post'),
    path('choose_user_type/', views.choose_user_type,
          name='choose_user_type'),
    path('search/', views.search, name='search'),
    path('book_tutoring_session/', views.book_tutoring_session,
         name='book_tutoring_session'),
    path('approving_session/', views.approve_session_request,
         name='approving_sessions'),
    path('deleting_session/', views.delete_session_request, name='deleting_session'),
    path('go_mailbox/', views.go_mailbox, name="go_mailbox"),
    path('switch/', views.change_user_type, name="switch"),
    path('profile/', views.go_profile, name='profile'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('read_notification/<path:id>/', views.read_notification, name='read_notification'),
    path('edit_posts/', views.edit_posts, name = "edit_posts"),
]

# path('', views.home, name='home'),
# path('', include("allauth.urls")),

tutorme/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.contrib.postgres.fields import ArrayField

# Philosophy is to have two user types so that tutors can post hourly rates and courses they can tutor

# We use the default user object to tutorme, so making tutor/tutee objects will then pass the user object in
# as a parameter (using one-to-one methodology in Django)
# need variables for hourly rate and courses (diff hourly rates for diff courses?
# need variable for available time frames

#sources:
#https://docs.djangoproject.com/en/4.2/ref/models/fields/
#https://docs.djangoproject.com/en/4.2/topics/db/examples/many_to_many/
#https://docs.djangoproject.com/en/4.2/topics/db/examples/one_to_one/

class Person(models.Model):
    # username and password stored in User model by default
    TUTOR = 'Tutor'
    TUTEE = 'Tutee'
    NOT_DECIDED = 'Not_Decided'

    PERSON_TYPE_CHOICES = [
        (TUTOR, 'Tutor'),
        (TUTEE, 'Tutee'),
        (NOT_DECIDED, 'Not Decided'),
    ]

    person_type = models.CharField(
        max_length=11,
        choices=PERSON_TYPE_CHOICES,
        default=NOT_DECIDED,
    )

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    about_me = models.CharField(max_length=500, default='')

    # TUTOR ONLY VALUES

    # TUTEE ONLY VALUES
    # booked_sessions stores the session in some form. maybe store post id or something similar
    # currently place holder. dont know to store string or max_length of string
    # should default value be [] or None? change to None if error occures

    @admin.display(
        ordering='email',
    )
    def __str__(self):
        person_info = "first name: " + self.first_name + "\n" + \
            "last name: " + self.last_name + "\n" + "email: " + self.email

        return person_info


class Classes(models.Model):
    class_id = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    units = models.CharField(max_length=10)
    section_type = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.class_id + ": " + self.title


class Post(models.Model):
    # RETRIEVE SET OF TUTEES FROM POST: post.enrolled_tutee.all()
    # RETRIEVE SET OF POSTS FROM TUTEE: tutee.post_set.all()
    enrolled_tutee = models.ManyToManyField(Person)
    classes = models.ForeignKey(Classes, on_delete=models.CASCADE)

    # tutor/creator email is main link to tutor that created post
    creatorEmail = models.EmailField(blank=False, null=True)
    creatorName = models.CharField(max_length=500, default="")


    # concatinate sessionRangeStart and sessionRangeEnd (separated by one space) to make some kind of unique identifier for
    # posts tutors make(need condition to make it so that tutors cannot create tutoring sessions)
    # within same time range
    hash = models.CharField(max_length=100)

    # keep track of which tutees booked this session. Posts has a record of tutee and tutee has record of post

    hourly_fee = models.DecimalField(decimal_places=2, max_digits=5)
    location = models.CharField(max_length=150)

    # not sure how to deal with same person want to be both tutor and tutee yet
    online = models.BooleanField(default=False)

    # contact_info for any contact details (phone number, email, discord, etc.)
    contact_info = models.CharField(max_length=150)

    # create field for timeframe (is there a models.TimeField?)
    # comments for anything else that the poster wants to let the reader know
    comments = models.CharField(max_length=500)

    # post initally on display. when fully booked, display_post = False
    display_post = models.BooleanField(default=True)

    # default tutor session is one-on-one(capacity = 1). max capacity is 5 tutee per session
    max_capacity = models.IntegerField(
        default=1, validators=[MaxValueValidator(5)])
    current_capacity = models.IntegerField(default=0)

    # store range (start and end of session)
    sessionRangeStart = models.DateTimeField(null=True)
    sessionRangeEnd = models.DateTimeField(null=True)

    def __str__(self) -> str:
        tutor = Person.objects.get(email=self.creatorEmail)
        return tutor.first_name + tutor.last_name + ": " + self.classes.name + \
            "\n $" + str(self.hourly_fee) + "/hr " + self.location + " --- " + str(self.online) + \
            " " + self.contact_info + "\n"


class Session_Request(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    tutee = models.ForeignKey(Person, on_delete=models.CASCADE)
    creator_email = models.EmailField(blank=False, null=True)
    # pending or declined. accepted goes into scheduled sessions
    status = models.CharField(default="pending", max_length=10)
    tutor_message = models.CharField(default="", max_length=500)
    sessionStart = models.DateTimeField(null=True)
    sessionEnd = models.DateTimeField(null=True)


class Notification(models.Model):
    is_read = models.BooleanField(default=False)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    creatorEmail = models.EmailField(blank=False, null=True)
    recipientEmail = models.EmailField(blank=False, null=True)
    id = models.AutoField(primary_key=True)

tutorme/views.py
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from tutorme.models import Classes, Person, Post, Session_Request, Notification
from django.contrib import messages
import requests


sis_url = "https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01&term=1238"

#SOURCE:
#https://docs.python.org/3/library/datetime.html
def __get_person(request):
    if (str(request.user) == 'AnonymousUser'):
        return ""
    else:
        email = request.user.email
        return Person.objects.get(email=email)


# /social/signup wont redirect to login page
def signup_redirect(request):
    messages.error(request, "This email is already being used.")
    return HttpResponseRedirect(reverse("tutorme:login_user"))

@login_required(login_url='/login_user')
def start(request):
    # loads landing page
     return render(request, "home/landing_page.html", {})


def login_user(request):
    # lets user log in with both account created on website or google oauth

    # if user is logged in, redirect to choose_user_type page.
    # request.user.is_authenticated == True for successful google oauth login
    if request.user.is_authenticated:
        return redirect(reverse("tutorme:choose_user_type"))

    else:
        if request.method == "POST":
            # user email is username
            username = request.POST["email"]
            password = request.POST["password"]

            # authenticate with username and password
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Logged in as " + user.first_name + ".")
                # send user to choose tutor/tutee option which will redirect to correct home page
                return redirect(reverse("tutorme:choose_user_type"))
            else:
                messages.error(
                    request,
                    "Login failed due to incorrect username or password. Please try again.",
                )
                return redirect("tutorme:login_user")
        else:
            return render(request, "login/login.html", {})


def __createClass(c):
    Classes(
        c["subject"] + c["catalog_nbr"] + c["section_type"],
        c["subject"] + " " + c["catalog_nbr"],
        c["descr"],
        c["units"],
        c["section_type"],
    ).save()


def reset():  # cleaning out all classes and adding them all in
    Classes.objects.all().delete()
    depts = "AAS,ACCT,AIRS,ALAR,AM,AMST,ANTH,APMA,ARAB,ARAD,ARAH,ARCH,ARCY,ARH,ARTH,ARTR,ARTS,ASL,ASTR,BENG,BIMS,BIOC,BIOE,BIOL,BIOM,BIOP,BME,BUS,CASS,CE,CELL,CHE,CHEM,CHIN,CHTR,CJ,CLAS,COGS,COLA,COMM,CONC,CPE,CPLT,CREO,CS,DANC,DEM,DH,DRAM,DS,EALC,EAST,ECE,ECON,EDHS,EDIS,EDLF,EDNC,EGMT,ELA,ENAM,ENCR,ENCW,ENEC,ENGL,ENGN,ENGR,ENLS,ENMC,ENMD,ENNC,ENPG,ENPW,ENRN,ENSP,ENTP,ENVH,ENWR,EP,ESL,ETP,EURS,EVAT,EVEC,EVGE,EVHY,EVSC,FORU,FREN,FRLN,FRTR,GBAC,GBUS,GCCS,GCNL,GCOM,GDS,GERM,GETR,GHSS,GNUR,GREE,GSAS,GSCI,GSGS,GSMS,GSSJ,GSVS,HBIO,HEBR,HETR,HHE,HIAF,HIEA,HIEU,HILA,HIME,HIND,HISA,HIST,HIUS,HR,HSCI,HUMS,IHGC,IMP,INST,ISBU,ISCP,ISED,ISHU,ISIN,ISLS,ISSS,IT,ITAL,ITTR,JAPN,JPTR,JWST,KICH,KINE,KLPA,KOR,KRTR,LAR,LASE,LAST,LATI,LAW,LING,LNGS,LPPA,LPPL,LPPP,LPPS,MAE,MATH,MDST,MED,MESA,MEST,MICR,MISC,MSE,MSP,MUBD,MUEN,MUPF,MUSI,NASC,NCAR,NCBM,NCBS,NCCJ,NCCS,NCDS,NCED,NCEN,NCFA,NCFL,NCHP,NCIS,NCLE,NCPD,NCPH,NCPR,NCSS,NCTH,NESC,NMVS,NUCO,NUIP,NURS,PASH,PATH,PAVS,PC,PERS,PETR,PHAR,PHIL,PHS,PHY,PHYS,PLAC,PLAD,PLAN,PLAP,PLCP,PLIR,PLPT,PLSK,PMCC,POL,PORT,POTR,PPL,PSCJ,PSED,PSHM,PSHP,PSLP,PSLS,PSPA,PSPL,PSPM,PSPS,PSSS,PST,PSTS,PSWD,PSYC,RELA,RELB,RELC,RELG,RELH,RELI,RELJ,RELS,RSC,RUSS,RUTR,SANS,SARC,SAST,SATR,SEC,SEMS,SLAV,SLFK,SLTR,SOC,SPAN,SPTR,STAT,STS,SWAH,SYS,TBTN,TURK,UD,UKR,UNST,URDU,USEM,WGS,XHOS,YIDD,YITR,ZFOR"
    deptList = depts.split(",")
    for det in deptList:
        print("Adding " + det)
        __add_classes(det)


def __add_classes(dept, cat_num):
    exact = []
    page = 1
    while True:
        searched = requests.get(
            sis_url + "&page=" + str(page) + "&subject=" + dept
        ).json()
        if len(searched) == 0:
            break
        exact += searched
        page += 1
    for c in exact:
        __createClass(c)

    exact = []
    page = 1
    while True:
        searched = requests.get(
            sis_url + "&page=" + str(page) + "&catalog_nbr=" + cat_num
        ).json()
        if len(searched) == 0:
            break
        exact += searched
        page += 1
    for c in exact:
        __createClass(c)


def __search_classes(dept, cat_num, course_name):
    # return list of classes objects if exists in database
    # else, create list of classes objects and return it
    # adds classes to database if not already in database

    if course_name:
        classes = Classes.objects.filter(title__icontains=course_name)
        name_list = course_name.split(" ")
        

        if len(classes) == 0: # check for stored classes with titles that are pieces of the searched
                for word in name_list:
                    classes = classes | (Classes.objects.filter(title__icontains=word))
                
        if len(classes) == 0:  # check sis
            exact = []
            page = 1
            searched_name = name_list[0]
            for i in range(1, len(name_list)):
                searched_name = searched_name + "_" + name_list[i]
            while True:
                searched = requests.get(
                        sis_url + "&page=" + str(page) + "&keyword=" + searched_name
                        ).json()
                if len(searched) == 0:
                    break
                exact += searched
                page += 1
            for c in exact:
                __createClass(c)
                classes = Classes.objects.filter(title=course_name)

        if len(classes) ==0:  # query api with pieces of the searched
            exact = []
            page = 1
            for word in name_list:
                while len(searched) == 0:
                    searched = requests.get(
                        sis_url + "&page=" + str(page) + "&keyword=" + word
                        ).json()
                    print("querying ", word)
                    print("searcged is ", len(searched), " items long")
                    if len(searched) == 0:
                        break
                    exact += searched
                    page += 1
                for c in exact:
                    __createClass(c)
                    classes = classes | Classes.objects.filter(title__icontains=word)

                        

    else:
        classes = Classes.objects.filter(class_id__icontains=dept + cat_num).order_by(
            "class_id"
        )
        print("there are ", len(classes), " with the dept ", dept)
        if len(classes) == 0:  # class not found --> Check API
            __add_classes(dept, cat_num)
            classes = (
                Classes.objects.filter(class_id__icontains=dept + cat_num).order_by(
                    "class_id"
                )
                | Classes.objects.filter(class_id__icontains=dept).order_by("class_id")
                | Classes.objects.filter(class_id__icontains=cat_num).order_by(
                    "class_id"
                )
            )

    return classes[:500]


def __search_posts(dept, cat_num, course_name, filter_by_date):
    classes = __search_classes(dept, cat_num, course_name)
    posts = set()
    for cl in classes:
        if not filter_by_date:
            for p in Post.objects.filter(classes=cl):
                posts.add(p)

        if filter_by_date:
            utc_time = datetime.utcnow()
            local_time = utc_time - timedelta(hours=4)
            for p in Post.objects.filter(
                classes=cl, sessionRangeEnd__gte=local_time
            ):
                posts.add(p)
    return list(posts)


def search(request):
    # search for classes using __search_classes()
    # and render it to search_class page if Tutor
    # or render it to search_post page if Tutee
    print("this is user", request.user)
    if (str(request.user) == 'AnonymousUser'):
        print("entered if")
        return HttpResponseRedirect(reverse("tutorme:login_user"))
    else:
        email=request.user.email
        unread_notifications = Notification.objects.filter(
            recipientEmail=email, is_read=False
        )

        if request.method == "POST":
            by_name = False
            course_name = request.POST["course_name_searched"]
            dept, cat_num = request.POST["dept_searched"], request.POST["catalog_searched"]
            if course_name:
                searched = course_name
                by_name = True  # search was based on course_name, refer to this value rather than dept and cat_num
            else:
                searched = dept + " " + cat_num

            already_requested_posts = set()
            registered_person = __get_person(request)
            if registered_person.person_type == "Tutor":
                classes = __search_classes(dept, cat_num, course_name)
                return render(
                    request,
                    "home/search_classes.html",
                    {
                        "searched": searched,
                        "classes": classes,
                        "by_name": by_name,

tutorme/templates/login/choose_user_type.html
{% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {%load socialaccount%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Choose User Type</title>
  </head>

  <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #525E9B;">
    <a class="navbar-brand">TutorMe</a>
    </nav>

  <style>
    .choose-user {
      padding-top: 40px;
      padding-left: 480px;
      padding-right: 480px;
    }
  </style>

  <body>
    <div class="container">
      <div class="choose-user">
        <h1 class="text-center mb-4">I am...</h1>
        {% comment %} include url redirect to back end function {% endcomment %}
        <form action="{%url 'tutorme:choose_user_type'%}" method="post">
          {% csrf_token %}
          <div class="form-group text-center">
            <input type="radio" id="tutee" name="user_type" value="tutee" />
            <label for="tutee">Looking for a Tutor</label><br />
            <br>
            <input type="radio" id="tutor" name="user_type" value="tutor" />
            <label for="tutor">A Tutor</label><br />
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary btn-block mt-4">Continue</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

tutorme/templates/login/creation_form.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
	<title>Account Creation Page</title>
	<!-- Link to Bootstrap stylesheet -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<!-- Custom CSS -->
	<style>
		.container {
			margin-top: 50px;
		}
	</style>
</head>

<nav class="navbar navbar-expand-md navbar-dark" style="background-color: #525E9B">
    <a class="navbar-brand" style="color:white">TutorMe</a>
    </nav>

{% if messages %}
	{% for message in messages %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Error!</strong>
        {{message}}
      </div>
	{% endfor %}
{% endif %}

<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<h2 class="text-center mb-4">Create An Account</h2>
				<form action = "" method = POST>
                    {% csrf_token %}
					<div class="form-group">
						<label for="first_name">First Name:</label>
						<input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter your first name">
					</div>
					<div class="form-group">
						<label for="last_name">Last Name:</label>
						<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter your last name">
					</div>
					<div class="form-group">
						<label for="email">Email:</label>
						<input type="email" class="form-control" id="email" name="email" placeholder="Enter your email">
					</div>
					<div class="form-group">
						<label for="password">Password:</label>
						<input type="password" class="form-control" id="password" name="password" placeholder="Enter a password">
					</div>
					<div class="form-group">
						<label for="confirm_password">Confirm Password:</label>
						<input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm your password">
					</div>
					<div>
						<button type="submit" class="btn btn-primary btn-block mt-4" style="background-color: #525E9B; border:none">Create Account</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- Link to jQuery and Bootstrap JavaScript libraries -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

tutorme/templates/login/login.html
{% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %} {%load socialaccount%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="style.css" />

    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #525E9B;">
    <a class="navbar-brand">TutorMe</a>
    </nav>
  </head>
  <br />
  <br />
  <body>
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-md-4 col-sm-6 col-xs-12">
          <form class="form-container" action="{%url 'tutorme:login_user'%}" method="POST">
            
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert">
                          ×
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            {% csrf_token %}
            <h3 class="text-center mb-3">Login</h3>
            <br />
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Email" name="email" />
            </div>
            <div class="form-group">
              <input type="password" class="form-control" placeholder="Password" name="password" />
            </div>
            <button type="submit" class="btn btn-primary btn-block" style="background-color:#525E9B; border:none">Login</button><br>
            <div>
              <h6 class="text-center">OR</h6>
            </div>
          </form>
        </div>
      </div>
    </div>

    <button class="btn btn-block btn-outline-info" style="width:30%; margin:auto">
      <a href="{% provider_login_url 'google' %}" style="display:block; text-decoration:none">
        <i class="fab fa-google"><img src="https://img.icons8.com/color/16/000000/google-logo.png"></i>
        Login with Google
      </a>
    </button>

    <div>
      <div class="form-group text-center mt-3">
        <a href="{% url 'tutorme:create_user' %}">Don't have an account? Sign Up!</a>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/esm/popper"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>